### ISSUE TITLE
Remove api where possible?

### ISSUE THREAD

**Issue by yagebu** [aumayr/beancount-web#7]
First of all thank you for the great work you've put into this! Not entirely satisfied with `bean-web`, I've written my own small web frontend for beancount a while ago, but this massively outperforms it.

At the moment performance is not great. I think in some cases it might be improved by removing the additional layer that the API introduces. The `_process_postings` functions is not really necessary in my opinion, as all of it could be done in the template (which has to know anyway what the data looks like) as far as I can see. I would submit an PR with this change if you don't oppose it.

Actually, I don't really think it makes sense to have the change and balance column in the general journal  as they just seem to keep track of all the currency conversions, for all accounts at once. What do you think about this? If the balances don't have to be calculated, the rendering of this page might be much quicker.

**Comment by aumayr** [comment]
The rationale behind `api.py` is the following: 

One day there will be a new module in `beancount.report` that returns all (for `beancount-web` required) views as Python-`dict`s and -`array`s, compatible with JSON (so no `datetime`, etc.). Right now `beancount.report` does return data to be displayed in a console, and HTML, and this (JSON) could be a third way of "rendering" the data. These methods should be highly optimized for performance and numerical correctness. If that one day really makes it's way into the `beancount`-repo, then `api.py` is redundant and will be removed. 

For the JSON-part: I want to keep all the `return`s in `api.py` JSON-serializeable (although they are called directly right now), because then, with very little overhead, `beancount-web` could run on an external server and call into a local `bean-report`. 

Right now `api.py` it is just a hacky placeholder for what could be in the future, and therefore I only tried to get the numbers required, and did not optimize for performance at all. 

But that future might be some time out, so working on it to make it faster (and numerically correcter) is still a good idea! I am currently working on refactoring it a bit to remove unused functions, etc., and will test the performance as well. If you already have the code ready please make a PR so I can see what you did there, but I might just copy over the important changes because I'm fairly far in the refactoring process. If you do not have code already then you should wait before you start coding on `api.py` until I pushed the refactoring, otherwise we will get merge errors. 

About `_process_postings(...)`: As described above the data has to be converted to `dict`s, but what would also help make it faster would be pagination! So if the _process_postings(...)` would have two new parameters (`offset` and `limit`) it would be possible to avoid many of those "costly" calls. What do you think about that? (And in that step ordering the journal from newest to oldest)

**Comment by yagebu** [comment]
Thank you for the explanation! Makes sense to not put too much logic into the templates, and keep the intense computational stuff in the api I guess.

I don't have a lot of code yet, so I'll wait for you to be done with the refactoring.

**Comment by aumayr** [comment]
I just pushed the refactoring: 69f8d47d667f6a2f381889a3f9c60c91f76b8600

I haven't tested if it has influence on the performance, but I guess that has not changed a lot. I am looking forward to what you came up with :-)
