### ISSUE TITLE
Save Beancount Queries

### ISSUE THREAD

**Issue by corani** [aumayr/beancount-web#96]
One of the distinctive features of Beancount is the ability to write `SQL` like queries to create custom reports. For example, today I needed to get an overview of my expenses per month over the last year:

```sql
SELECT
  MONTH(date) AS month,
  SUM(COST(position)) AS balance
WHERE
   account ~ 'Expenses:' AND
   currency = 'CNY' AND
   YEAR(date) = 2015
GROUP BY 1
ORDER BY 1;
```

Instead of creating these queries from scratch every time (or having to save them elsewhere), it would be useful if it were possible to save them, right from the `Custom Query` page.

UI wise, I imagine a select box, `Save` and `Delete` button next to the existing `Submit Query` button. The select box would contain a list of saved queries and a `Save as new Query` option.

**Comment by aumayr** [comment]
This would definitely save some time! 

What I like about `beancount-web` is that it is "stateless", in the sense that it does not have it's own database. All data is coming from `api.py` and the `.conf`-file. 

I think we should keep it that way, even when implementing a feature like this. So in order to implement this, the following would keep it that way (in my mind, anyway ;-) ):

 - Store the queries (strings) in a plain text file
 - Specify the location of that file in the `.conf`-file

**Comment by aumayr** [comment]
I will create a new branch and take a shot at it.

**Comment by corani** [comment]
Great, plain text file for the queries is what I had in mind as well. Maybe something like:

```ini
[Expenses per month]
SELECT
  MONTH(date) AS month,
  SUM(COST(position)) AS balance
WHERE
   account ~ 'Expenses:' AND
   currency = 'CNY' AND
   YEAR(date) = 2015
GROUP BY 1
ORDER BY 1;

[Balances from 2015]
balances from year = 2015
```

**Comment by aumayr** [comment]
@corani I added a first draft of the code in e0e7319. Can you try and report back if this fits your needs?

**Comment by corani** [comment]
You're almost there! This is working a treat.

A couple of issues I found:
- if the stored-queries file doesn't exist, it should be created
- `~` to indicate the user's home folder doesn't work 
- After saving a query, the select box isn't updated until after the page is reloaded
- Selecting the first "empty" option from the select box doesn't clear the query editor
- After you press `Submit Query`, the select box defaults back to the "empty" option
- If you press `Cancel` in the `Query Title` dialog, the query is saved anyway, but with an empty name
- You can save multiple queries under the same name
- When you press `Store query` after loading an existing query, it should ask to overwrite the existing query, instead of saving it as a new one

**Comment by aumayr** [comment]
Thanks for the feedback! Some of those suggestions are so obvious that I don't know how I could have missed them... will implement them in the coming days.

Another idea: Why not share the queries with others? Would work like follows:

- Public Github-Repo with the queries
- Display some as examples on the Query-page (randomly choosen)
- Make a website to display them all, with syntax highlighting, a description for each query, and maybe a way to comment on them. The queries would be fetched from the repository as well. 
- A way to submit new queries (beside PRs against the Repo)

What do you think?

**Comment by corani** [comment]
Since that is going quite a ways beyond this feature, it'd probably be better to create a new feature for that. I like the idea, but this could be something quite separate from beancount-web, since it would probably require a public server component.

We should probably get some input on this from Martin and the beancount mailing list as well, as it'd be useful to them too.

**Comment by aumayr** [comment]
Absolutely correct!

**Comment by aumayr** [comment]
@corani Before I write something on the mailing list I just quickly want to show you how this could look like and politely ask for feedback: http://aumayr.github.io/beancount-sql-queries/

**Comment by aumayr** [comment]
> if the stored-queries file doesn't exist, it should be created

7e5e9fbf5507933a142ae760b239a1a033cc101b

> ~ to indicate the user's home folder doesn't work

096b0f74c4042358a2fa59b7c71bf15588b12238

> After saving a query, the select box isn't updated until after the page is reloaded
> After you press Submit Query, the select box defaults back to the "empty" option


25401b96ae74203a9d1446961b44c7cb2646d459
d93e4eca0e93bce6ba7444287fac2a3a4c1de186

> Selecting the first "empty" option from the select box doesn't clear the query editor

0b87201151f97c5c8cbbb6f8dfcf3fd76f1f522c

> If you press Cancel in the Query Title dialog, the query is saved anyway, but with an empty name

4b835ba8816216a328576fc27a5d4acb3d403c2f

> You can save multiple queries under the same name

f04c98cbaae29740fb395b5c5e14c43696d71c83

@corani Still missing:

> When you press Store query after loading an existing query, it should ask to overwrite the existing query, instead of saving it as a new one

**Comment by corani** [comment]
Looks good, one (inline) comment for `create file if it doesn't exist`: It should also (attempt) to create the path. I'll give it a spin later today and let you know if I still find anything.

**Comment by corani** [comment]
It's working great.

I've added a `Delete Query` option as well.

By the way, we may need to have to rethink the current query reference-by-index, since this'll cause issues when editing queries from more than one location at the same time.

**Comment by yagebu** [comment]
As beancount actually supports a `Query` directive, another possible place to store (and definitely read) them would be in the beancount file (we could at least generate the entries so that you can just copy-paste them to the file). It's an experimental feature, but I think this is a good place to discuss if they're generally useful. Would be nice if this was not just something `beancount-web` specific :)

@blais What do you think? Is the `Query` directive here to stay?

**Comment by corani** [comment]
Interesting. I'd definitely be in favor of pulling it up into beancount, if that is possible.

**Comment by aumayr** [comment]
Merged the PR from @corani into `master`, which adds this functionality via the `query` directives suggested by @yagebu. 

What is missing is correct syntax highlighting in the Source editor for these multi-line strings. 

@corani What should we do with the other work in the `store-custom-queries`-branch (storing the queries in a file)? Discard it?

And do you have feedback for  http://aumayr.github.io/beancount-sql-queries/?

**Comment by corani** [comment]
As useful as `store-custom-queries` is, I believe #104 is more elegant and in-line with the beancount philosophy. Using the `Query` directive may be one more step than being able to store the queries directly, but it has the added benefit of the queries being available to beancount as well, plus not needing an extra file.

We should wait on @blais for confirmation that this directive is there to stay, before discarding `store-custom-queries`.

**Comment by corani** [comment]
The `beancount-sql-queries` looks fine, but I don't think it'll stay usable after collecting a few dozen queries. Maybe some kind of wiki would be an option?

**Comment by blais** [comment]
On Thu, Jan 14, 2016 at 7:26 AM, Jakob Schnitzer <notifications@github.com>
wrote:

> As beancount actually supports a Query directive, another possible place
> to store (and definitely read) them would be in the beancount file (we
> could at least generate the entries so that you can just copy-paste them to
> the file). It's an experimental feature, but I think this is a good place
> to discuss if they're generally useful. Would be nice if this was not just
> something beancount-web specific :)
>
> @blais <https://github.com/blais> What do you think? Is the Query
> directive here to stay?
>
Yes, unless it's proven to be problematic over usage.

My only doubts are because there's no reporting script making use of them
right now, and I don't like to have unused fluff around too much, but if
you're using it, I could move it from being experimental to being permanent.

**Comment by blais** [comment]
I had originally created a doc to gather feedback and user queries here:

https://docs.google.com/document/d/1uHonpRkbZ5wMCoZtzCBSBrl959Ciy4gq4aTB7A-m8Uk/edit#heading=h.i0jeumnvcgbd

The doc has gone a bit stale over the piling amount of other things to do.
I need to reconcile all the TODO lists I have into the beancount/TODO file
and clean that up at some point.

**Comment by corani** [comment]
That's great, @aumayr I think in that case we can discard `store-custom-queries`.

@blais I was thinking that it might be useful in beancount to let bean-report run these canned queries, so you can do e.g. `bean-report "expenses per month"` in the same way as you can do `bean-report balances`

**Comment by blais** [comment]
Yes, that's what I have in mind, or a way to run all the queries
automatically, something like a better version of this that uses input from
the input file instead of hardcoding the queries:

https://bitbucket.org/blais/beancount/src/0f41ec6f15e12ced44b4571a5f2ef85b2f875e30/src/python/beancount/plugins/split_expenses.py?at=default&fileviewer=file-view-default#split_expenses.py-218

I think it will be an extension of bean-query, e,g

  bean-query --run $FILENAME

would run all the queries and output on the console, or something like that.

**Comment by corani** [comment]
I noticed that you support (at least with the query directive) multi-line strings using single double-quotes (`" ... "`). Do you think it would be a good idea to do multi-line strings with triple double-quotes (`""" ... """`)?

This would avoid problems when queries contain quotes, and make adding embedded SQL syntax highlighting within beancount-web a bit easier.

**Comment by blais** [comment]
I haven't thought about this so much but at the write I added this I
thought because of the requirements of the language it wasn't necessary to
escape multi-line strings in this way, though I admit I've witness syntax
highlighting problems a few times. I'm not opposed to changing the parser
to add this in.

**Comment by corani** [comment]
@blais should I open a bitbucket issue for adding triple-quoted strings?

**Comment by blais** [comment]
Sure. But I already created an entry in the TODO file.

**Comment by aumayr** [comment]
As this is now implemented in `beancount-web´ I will close this issues. Thanks everybody for the work!
